# Generated by Django 3.1.4 on 2021-01-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
