# Generated by Django 3.1.4 on 2021-01-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
